Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                         count    min threads    max threads
------------------------  -------  -------------  -------------
all                             1              1              1
an_table                        1             12             12
gatk_variantstotable_PSG        2              6              6
merge_dataframes                1             12             12
table_step1_PSG                 2              1              1
table_step2_PSG                 2              6              6
total                           9              1             12

Select jobs to execute...

[Tue Dec 27 14:48:09 2022]
rule gatk_variantstotable_PSG:
    input: annotated/annotated_all_snps_GF6.ON_multianno.vcf, pseudogenomes/GF6/GF6_GCF_001858045.2.fa
    output: variants/AD_GT_counts_bi_GF6.table
    log: logs/gatk/var2table/snvs_GF6.log
    jobid: 4
    reason: Missing output files: variants/AD_GT_counts_bi_GF6.table
    wildcards: pseudo=GF6
    threads: 6
    resources: tmpdir=/tmp, mem_mb=6000

[Tue Dec 27 14:48:09 2022]
Error in rule gatk_variantstotable_PSG:
    jobid: 4
    input: annotated/annotated_all_snps_GF6.ON_multianno.vcf, pseudogenomes/GF6/GF6_GCF_001858045.2.fa
    output: variants/AD_GT_counts_bi_GF6.table
    log: logs/gatk/var2table/snvs_GF6.log (check log file(s) for error message)
    conda-env: /home/fish/Snakemake_for_SNPs/workflow/.snakemake/conda/cc9537fc1e1a43ea37b10ee499f035dc_

RuleException:
CalledProcessError in line 19 of /home/fish/Snakemake_for_SNPs/workflow/rules/variants_to_table.smk:
Command 'set -euo pipefail;  /home/fish/anaconda3/envs/pipeline/bin/python /home/fish/Snakemake_for_SNPs/workflow/.snakemake/scripts/tmp1caajr4n.variantstotable.py' returned non-zero exit status 1.
  File "/home/fish/Snakemake_for_SNPs/workflow/rules/variants_to_table.smk", line 19, in __rule_gatk_variantstotable_PSG
  File "/home/fish/anaconda3/envs/pipeline/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-12-27T144808.539822.snakemake.log
