Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                   count    min threads    max threads
------------------  -------  -------------  -------------
all                       1              1              1
combine_gvcfs_PSG0        1              6              6
combine_gvcfs_PSG1        1              6              6
total                     3              1              6

Select jobs to execute...

[Tue Dec 27 10:43:27 2022]
rule combine_gvcfs_PSG0:
    input: calls/GF6_GF6.g.vcf, calls/KF6_GF6.g.vcf, calls/GS4_GF6.g.vcf, calls/KS4_GF6.g.vcf, genome/Tilapia_NC_031967.2_GCF_001858045.2.fa
    output: calls/all_g_GF6.vcf
    log: logs/gatk/combinegvcfs/combinegvcfs_GF6.log
    jobid: 1
    reason: Missing output files: calls/all_g_GF6.vcf
    threads: 6
    resources: tmpdir=/tmp, mem_mb=6000

[Tue Dec 27 10:43:27 2022]
rule combine_gvcfs_PSG1:
    input: calls/GF6_KS4.g.vcf, calls/KF6_KS4.g.vcf, calls/GS4_KS4.g.vcf, calls/KS4_KS4.g.vcf, genome/Tilapia_NC_031967.2_GCF_001858045.2.fa
    output: calls/all_g_KS4.vcf
    log: logs/gatk/combinegvcfs/combinegvcfs_GF6.log
    jobid: 28
    reason: Missing output files: calls/all_g_KS4.vcf
    threads: 6
    resources: tmpdir=/tmp, mem_mb=6000

[Tue Dec 27 10:43:27 2022]
Error in rule combine_gvcfs_PSG1:
    jobid: 28
    input: calls/GF6_KS4.g.vcf, calls/KF6_KS4.g.vcf, calls/GS4_KS4.g.vcf, calls/KS4_KS4.g.vcf, genome/Tilapia_NC_031967.2_GCF_001858045.2.fa
    output: calls/all_g_KS4.vcf
    log: logs/gatk/combinegvcfs/combinegvcfs_GF6.log (check log file(s) for error message)
    conda-env: /home/fish/Snakemake_for_SNPs/workflow/.snakemake/conda/cc9537fc1e1a43ea37b10ee499f035dc_

[Tue Dec 27 10:43:27 2022]
Error in rule combine_gvcfs_PSG0:
    jobid: 1
    input: calls/GF6_GF6.g.vcf, calls/KF6_GF6.g.vcf, calls/GS4_GF6.g.vcf, calls/KS4_GF6.g.vcf, genome/Tilapia_NC_031967.2_GCF_001858045.2.fa
    output: calls/all_g_GF6.vcf
    log: logs/gatk/combinegvcfs/combinegvcfs_GF6.log (check log file(s) for error message)
    conda-env: /home/fish/Snakemake_for_SNPs/workflow/.snakemake/conda/cc9537fc1e1a43ea37b10ee499f035dc_

RuleException:
CalledProcessError in line 39 of /home/fish/Snakemake_for_SNPs/workflow/rules/combine_gvcfs_pseudo.smk:
Command 'set -euo pipefail;  /home/fish/anaconda3/envs/pipeline/bin/python /home/fish/Snakemake_for_SNPs/workflow/.snakemake/scripts/tmpvdkok8l4.combinegvcfs.py' returned non-zero exit status 1.
  File "/home/fish/Snakemake_for_SNPs/workflow/rules/combine_gvcfs_pseudo.smk", line 39, in __rule_combine_gvcfs_PSG1
  File "/home/fish/anaconda3/envs/pipeline/lib/python3.7/concurrent/futures/thread.py", line 57, in run
RuleException:
CalledProcessError in line 20 of /home/fish/Snakemake_for_SNPs/workflow/rules/combine_gvcfs_pseudo.smk:
Command 'set -euo pipefail;  /home/fish/anaconda3/envs/pipeline/bin/python /home/fish/Snakemake_for_SNPs/workflow/.snakemake/scripts/tmpkj5bx9qh.combinegvcfs.py' returned non-zero exit status 1.
  File "/home/fish/Snakemake_for_SNPs/workflow/rules/combine_gvcfs_pseudo.smk", line 20, in __rule_combine_gvcfs_PSG0
  File "/home/fish/anaconda3/envs/pipeline/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-12-27T104326.994169.snakemake.log
